version: '3.8'

services:
  postgres:
  image: postgres:16.0-alpine3.18
  restart: unless-stopped
  networks:
      - postgres
  ports:
    - "5432:5432"
  environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
  volumes:
    - "/var/app/dbdata:/var/lib/postgresql/data"

networks:
  postgres:
  name: postgres
